### ISSUE TITLE
EU Flag Request

### ISSUE THREAD

**Issue by emylee9** [ekiziltas/material-ui-flags#8]
New Server Addition! Would an EU Flag be possible? 

![1280px-Flag_of_Europe svg](https://user-images.githubusercontent.com/5739699/98965015-c3adbd80-24c6-11eb-9ba7-c6e98fdc8601.png)

**Comment by ekiziltas** [comment]
Dear @emylee9, EU flag is added, regards :)

**Comment by emylee9** [comment]
Perfect, thanks!
