### ISSUE TITLE
Where did all the other flags go?

### ISSUE THREAD

**Issue by darryl-snow** [ekiziltas/material-ui-flags#9]

**Comment by Industrial** [comment]
"other" ?

**Comment by darryl-snow** [comment]
There are only 15 flags: https://github.com/ekiziltas/material-ui-flags/blob/master/lib/index.js

But there are more than 15 countries.

**Comment by ekiziltas** [comment]
Dear @darryl-snow, if you need further flags to be implemented, just let me know. Thanks.
